### ISSUE TITLE
Event Position Requests

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtt#287] opened 2016-08-07 18:03 UTC
Let's making asking to be a run position a two click process!

For any unassigned event position, I'd like the (unassigned) text to be a link that will request that event position. A possible design could be:

1. User clicks (unassigned)
2. Pop-up modal box appears containing: 
Requesting to {{position_name}} {{event_name}}
Text field to provide additional message
Cancel/Send buttons
3. User clicks send and an email is sent, or cancel and the modal goes away

The email that the request gets sent to should follow the following chain:
aPosition -> Position -> TiC -> Exec -> abtech+position@andrew

If the position above any position is unfilled it should traverse up to the next person. For example, if someone wanted to aFoH but there was no FoH, the request should be sent to the TiC. If someone wants to TiC an event and there is an Exec member assigned to that event, the exec member should get the email.

If that hierarchy thing is a pain to implement, we can just have all emails sent to abtech+position@andrew

**Comment by tedgarb** [comment] 2016-08-07 18:05
Duplicate of #280

**Closed by tedgarb** 2016-08-07 18:05 UTC
Labels: Feature
